[Tabular][fastai] Refactoring
awslabs/autogluon pull request #829
Opened 2020-12-17 03:16 UTC by gradientsky

*Description of changes:*
- extracted and reused model-specific feature from tabular NN into fastai tabular NN
- refactoring of fastai code

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-17 03:19 UTC, gradientsky commented on tabular/src/autogluon/tabular/models/fastainn/metrics.py
> +def get_objective_func_name(problem_type, stopping_metric):
These just moved into separate file to improve readability, no actual change

2020-12-17 03:19 UTC, gradientsky commented on tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
> -    def _create_preprocessor(self, impute_strategy, max_category_levels):
just moved into separate file to enable reuse, no functional change

2020-12-17 03:19 UTC, gradientsky commented on tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_preprocessor.py
> +class TabularNeuralNetPreprocessor(object):
just moved into separate file to enable reuse, no functional change

2020-12-17 04:18 UTC, szha commented
Job PR-829-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-829/1/index.html

2020-12-17 21:41 UTC, Innixma requested changes
Marking this as request changes to ensure it isn't merged prior to benchmarking.

- [ ] Benchmark on AutoMLBenchmark to ensure performance and stability are not degraded.

2020-12-19 06:20 UTC, jwmueller approved these changes
Code looks good to me. 

When benchmarking it could also be good to look at whether:
1) this change improves FastAI model
2) this change improves autogluon-ensemble (I'd have slight worry that sharing common preprocessing between MXNet and FastAI nets may reduce ensemble diversity, even if it does help FastAI nets individually)

2020-12-19 06:23 UTC, Innixma commented
> Code looks good to me.
> 
> When benchmarking it could also be good to look at whether:
> 
> 1. this change improves FastAI model
> 2. this change improves autogluon-ensemble (I'd have slight worry that sharing common preprocessing between MXNet and FastAI nets may reduce ensemble diversity, even if it does help FastAI nets individually)

I also feel that the ensemble score might drop if the gains are only minor for FastAI, so it will be interesting to see the results.

2021-01-26 18:00 UTC, closed without merging